spring.application.name=backend

# 1. DATABASE CONNECTION (Updated to PostgreSQL)
# Ensure 'healthchain_db' matches the name you created in pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/healthchain_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. SERVER CONFIGURATION
server.port=8085

# 3. JPA / HIBERNATE SETTINGS
# 'update' will create the table/columns automatically if they don't exist
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 4. ERROR HANDLING
server.error.include-message=always